services:
  db:
    image: postgres:15
    ports:
        - 5432:5432
    environment:
        - POSTGRES_PASSWORD=example

  hasura:
    image: hasura/graphql-engine:latest
    ports:
        - 8080:8080
    depends_on:
        - db
    environment:
        HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:example@db:5432/postgres
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true"